version: '3.8'

services:
  app:
    image: news_jenkins
    ports:
      - "5000:5000"
    network_mode: my_net
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    network_mode: my_net
    volumes:
      - db-data:/var/lib/mysql
networks:
  my_net:

volumes:
  db-data:
